export const ProductListsData = [
  {
    id: 1,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00008-768x764.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 2,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00007-768x768.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 3,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00006-768x968.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 4,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00005-768x958.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 5,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00004-768x972.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 6,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00003-768x971.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 7,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00002-768x955.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 8,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00007-768x768.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 9,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/image00001-768x958.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 10,
    url: "https://artbyraff.com/wp-content/uploads/2023/06/change-768x968.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
  {
    id: 11,
    url: "https://artbyraff.com/wp-content/uploads/2022/04/WhatsApp-Image-2022-04-26-at-16.38.24-768x1024.jpeg",
    title: "Untitled 202III – Series",
    productprice: "Sold",
    productcatagori: "Material: Material : mixed media on canvas",
    productdescription: "100 x 100 cm",
  },
];
